### ISSUE TITLE
Вечный цикл при разборе приёмного буфера

### ISSUE THREAD

**Issue by ViacheslavMezentsev** [AndreyTulyakov/ros2_crsf_receiver#1]
Рекомендую вот [сюда](https://github.com/AndreyTulyakov/ros2_crsf_receiver/blob/master/crsf_receiver/src/crsf_parser.cpp#L29) добавить такую строку:

`rx_buffer.erase( rx_buffer.begin() );`

Иначе тушка далеко не уползёт или не улетит. Это временный костыль (см. [тут](https://godbolt.org/z/obxchnWvz)).

**Comment by AndreyTulyakov** [comment]
Спасибо за участие и наглядный пример!
 
Хотя такой пакет хоть и не ожидаем, но действительно способен сломать парсер.

Сделал комит с правкой - принудительный сдвиг буфера.

**Comment by ViacheslavMezentsev** [comment]
Это только кажется, что такие пакеты не ожидаемы. В примере только один такой вариант.

Я запостил сюда решение, т.к. без него в моих тестах декодер гарантировано уходит в вечный цикл всегда при реальном применении.
Найти ошибку в логике работы было не так просто, особенно, если не видишь полной картины того, что происходит.

Я тестировал с приёмником ELRS, который выдаёт пакеты CRSF через несколько мсек. Уход в вечный цикл был всегда, но через разное время. В среднем через 15 мин работы.

Костыль, который я предложил, нужен для функции _shift_left_rx_buffer_until_byte_(), которая на самом деле не сдвигает буфер, как заявлено, из-за особенности работы метода _erase_(), когда key встречается первым.

Ничто не мешает байту 0xC8 оказаться внутри пакета или являться значением CRC8. Также работа декодера вполне может начаться с неполного пакета. Кроме того, ошибки на линии тоже имеют некоторую вероятность, поэтому нужна CRC8. Получается, если звёзды сходятся, то кирпич очень даже вероятен. В моём случае, как я писал выше, он гарантированный, но отложенный.
